sugarcube-2:
  macros:
    dialog:
      name: dialog
      container: true
    notify:
      name: notify
      container: true
    collapsible:
      name: collapsible
      container: true
    updateStat:
      name: updateStat
